# Generated by Django 6.0 on 2026-01-06 21:36

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marker_type', models.CharField(choices=[('incident', 'Incident'), ('service', 'Emergency Service'), ('checkpoint', 'Police Checkpoint'), ('safe_zone', 'Safe Zone'), ('danger', 'High Danger Area')], max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(default='map-marker', max_length=50)),
                ('color', models.CharField(default='#ff0000', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'map_markers',
            },
        ),
        migrations.CreateModel(
            name='SafetyZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('zone_type', models.CharField(choices=[('neighborhood', 'Neighborhood'), ('ward', 'Ward'), ('constituency', 'Constituency'), ('county', 'County'), ('custom', 'Custom Zone')], max_length=20)),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('safety_score', models.FloatField(default=0.0)),
                ('incident_count_24h', models.IntegerField(default=0)),
                ('incident_count_7d', models.IntegerField(default=0)),
                ('incident_count_30d', models.IntegerField(default=0)),
                ('crime_risk', models.FloatField(default=0.0)),
                ('accident_risk', models.FloatField(default=0.0)),
                ('hazard_risk', models.FloatField(default=0.0)),
                ('police_stations', models.IntegerField(default=0)),
                ('hospitals', models.IntegerField(default=0)),
                ('fire_stations', models.IntegerField(default=0)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('area_sq_km', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_incident_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'safety_zones',
                'indexes': [models.Index(fields=['zone_type', 'safety_score'], name='safety_zone_zone_ty_7a4202_idx'), models.Index(fields=['boundary'], name='zone_boundary_idx')],
            },
        ),
        migrations.CreateModel(
            name='HeatMapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(max_length=50)),
                ('intensity', models.FloatField(default=0.0)),
                ('data_points', models.JSONField(default=list)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heatmap_data', to='maps.safetyzone')),
            ],
            options={
                'db_table': 'heatmap_data',
            },
        ),
    ]
