# Generated by Django 6.0 on 2026-01-06 21:36

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('service_type', models.CharField(choices=[('police', 'Police Station'), ('hospital', 'Hospital'), ('fire', 'Fire Station'), ('ambulance', 'Ambulance Service'), ('rescue', 'Rescue Service'), ('clinic', 'Clinic'), ('pharmacy', '24/7 Pharmacy'), ('helpline', 'Helpline')], max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('phone_number_2', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('address', models.TextField()),
                ('county', models.CharField(max_length=100)),
                ('constituency', models.CharField(blank=True, max_length=100, null=True)),
                ('ward', models.CharField(blank=True, max_length=100, null=True)),
                ('operational_hours', models.CharField(default='24/7', max_length=100)),
                ('is_24_7', models.BooleanField(default=True)),
                ('services_offered', models.TextField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('average_rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_ratings', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'emergency_services',
            },
        ),
        migrations.CreateModel(
            name='PoliceInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('positive', 'Positive Interaction'), ('negative', 'Negative Interaction'), ('neutral', 'Neutral Interaction'), ('harassment', 'Harassment'), ('bribery', 'Bribery Request'), ('professional', 'Professional Service')], max_length=20)),
                ('description', models.TextField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('address', models.TextField()),
                ('police_station', models.CharField(blank=True, max_length=200, null=True)),
                ('officer_badge', models.CharField(blank=True, max_length=50, null=True)),
                ('officer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('officer_description', models.TextField(blank=True, null=True)),
                ('anonymous', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
                ('verification_count', models.IntegerField(default=0)),
                ('incident_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='police_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'police_interactions',
                'ordering': ['-incident_date'],
            },
        ),
        migrations.CreateModel(
            name='SafetyTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General Safety'), ('home', 'Home Safety'), ('travel', 'Travel Safety'), ('cyber', 'Cyber Safety'), ('emergency', 'Emergency Preparedness'), ('health', 'Health Safety')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Emergency')], default='low', max_length=20)),
                ('icon', models.CharField(default='lightbulb', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'safety_tips',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('response_time_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('professionalism_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='emergency.emergencyservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_reviews',
            },
        ),
        migrations.AddIndex(
            model_name='emergencyservice',
            index=models.Index(fields=['service_type', 'county'], name='emergency_s_service_fd22bc_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyservice',
            index=models.Index(fields=['location'], name='service_location_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicereview',
            unique_together={('service', 'user')},
        ),
    ]
