# Generated by Django 6.0 on 2026-01-06 21:36

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(default='exclamation-triangle', max_length=50)),
                ('color', models.CharField(default='#ff6b6b', max_length=20)),
                ('severity_weight', models.IntegerField(default=1)),
                ('requires_verification', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Incident Categories',
                'db_table': 'incident_categories',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('incident_type', models.CharField(choices=[('crime', 'Criminal Activity'), ('accident', 'Road Accident'), ('hazard', 'Public Hazard'), ('checkpoint', 'Police Checkpoint'), ('sos', 'SOS/Emergency'), ('police_interaction', 'Police Interaction'), ('other', 'Other Incident')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Emergency')], default='medium', max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('address', models.CharField(max_length=500)),
                ('county', models.CharField(max_length=100)),
                ('constituency', models.CharField(blank=True, max_length=100, null=True)),
                ('ward', models.CharField(blank=True, max_length=100, null=True)),
                ('anonymous', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_count', models.IntegerField(default=0)),
                ('false_report_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('verified', 'Verified'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('false_report', 'False Report'), ('closed', 'Closed')], default='reported', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('media_files', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_incidents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_incidents', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='incidents.incidentcategory')),
            ],
            options={
                'db_table': 'incidents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='incident_media/%Y/%m/%d/')),
                ('file_type', models.CharField(max_length=20)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='incident_thumbnails/')),
                ('blurred', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='incidents.incident')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'incident_media',
            },
        ),
        migrations.CreateModel(
            name='IncidentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='incidents.incident')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'incident_verifications',
            },
        ),
        migrations.CreateModel(
            name='SafetyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('alert_type', models.CharField(choices=[('incident', 'New Incident'), ('trend', 'Area Trend'), ('emergency', 'Emergency Alert'), ('system', 'System Update')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Emergency')], max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('radius_km', models.FloatField(default=5.0)),
                ('counties', models.JSONField(blank=True, default=list)),
                ('target_user_types', models.JSONField(blank=True, default=list)),
                ('send_email', models.BooleanField(default=True)),
                ('send_sms', models.BooleanField(default=False)),
                ('send_push', models.BooleanField(default=True)),
                ('sent_count', models.IntegerField(default=0)),
                ('delivered_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'safety_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status', 'severity'], name='incidents_status_31e4f5_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['county', 'created_at'], name='incidents_county_1cf17b_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['location'], name='incident_location_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='incidentverification',
            unique_together={('incident', 'user')},
        ),
    ]
